// СГЕНЕРИРОВАНО tool/generate_level_pages_test.dart —
// тем же генератором, что и страницы docs/levels/*.docx.
// Не редактировать вручную.
class LevelRoundFixture {
  final int level;
  final int gridSize;
  final List<List<int>> objects;
  final List<List<int>> obstacles;
  final List<int> objectIndex;
  final List<String> moves;
  final List<bool> expected;
  const LevelRoundFixture(this.level, this.gridSize, this.objects,
      this.obstacles, this.objectIndex, this.moves, this.expected);
}

const List<LevelRoundFixture> levelRoundFixtures = [
  LevelRoundFixture(2, 4, [[3, 3], [0, 2]], [],
      [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0],
      ['ВВ', 'ПП', 'ПП', 'ВВ', 'ЛЛ', 'НН', 'ЛЛ', 'ПП', 'ЛЛ', 'ЛЛ', 'НН', 'ПП', 'ВВ', 'ВВ', 'НН', 'НН'],
      [true, true, false, true, true, true, false, true, true, false, false, false, false, false, true, false]),
  LevelRoundFixture(2, 4, [[3, 0], [2, 3]], [],
      [0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1],
      ['ЛЛ', 'ВВ', 'НН', 'НН', 'ЛЛ', 'НН', 'ПП', 'ПП', 'ПП', 'ЛЛ', 'НН', 'ВВ', 'ЛЛ', 'ПП', 'ВВ', 'ВВ'],
      [true, true, true, false, false, true, false, true, false, true, false, true, false, false, false, true]),
  LevelRoundFixture(2, 4, [[3, 0], [3, 1]], [],
      [0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1],
      ['ЛЛ', 'НН', 'НН', 'ЛЛ', 'ВВ', 'ВВ', 'ПП', 'ЛЛ', 'ПП', 'ВВ', 'НН', 'ПП', 'ВВ', 'НН', 'ЛЛ', 'ПП'],
      [true, true, false, false, true, false, false, false, false, false, true, false, true, true, true, true]),
  LevelRoundFixture(2, 4, [[2, 1], [2, 2]], [],
      [1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
      ['ЛЛ', 'ВВ', 'ВВ', 'ПП', 'НН', 'НН', 'ПП', 'НН', 'ПП', 'ВВ', 'ВВ', 'ЛЛ', 'ПП', 'ЛЛ', 'ЛЛ', 'НН'],
      [true, true, false, false, true, true, true, false, false, true, false, true, false, false, true, false]),
  LevelRoundFixture(2, 4, [[3, 1], [2, 1]], [],
      [0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0],
      ['ПП', 'ЛЛ', 'ПП', 'ВВ', 'НН', 'ВВ', 'НН', 'ПП', 'ВВ', 'ЛЛ', 'ВВ', 'ЛЛ', 'НН', 'ПП', 'ЛЛ', 'НН'],
      [false, true, false, false, true, true, true, true, false, true, false, false, true, false, true, false]),
  LevelRoundFixture(2, 4, [[0, 3], [3, 1]], [],
      [0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1],
      ['ПП', 'НН', 'ПП', 'ЛЛ', 'ЛЛ', 'ВВ', 'ВВ', 'НН', 'ПП', 'ЛЛ', 'НН', 'НН', 'ВВ', 'ПП', 'ЛЛ', 'ВВ'],
      [true, false, false, true, true, false, true, true, true, false, false, true, true, false, false, false]),
  LevelRoundFixture(2, 4, [[3, 0], [0, 2]], [],
      [0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1],
      ['ПП', 'ЛЛ', 'ВВ', 'ВВ', 'НН', 'ВВ', 'ВВ', 'ЛЛ', 'ПП', 'НН', 'ЛЛ', 'ПП', 'ЛЛ', 'НН', 'НН', 'ПП'],
      [false, true, true, false, true, true, false, false, true, true, false, false, false, false, true, true]),
  LevelRoundFixture(2, 4, [[3, 2], [2, 1]], [],
      [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0],
      ['ПП', 'ЛЛ', 'ПП', 'ВВ', 'НН', 'ВВ', 'ЛЛ', 'ЛЛ', 'НН', 'ПП', 'ВВ', 'НН', 'ЛЛ', 'ВВ', 'НН', 'ПП'],
      [false, true, false, true, true, true, false, false, true, false, true, true, false, false, true, false]),
  LevelRoundFixture(2, 4, [[3, 0], [2, 0]], [],
      [0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1],
      ['ЛЛ', 'НН', 'ВВ', 'НН', 'НН', 'НН', 'ЛЛ', 'ПП', 'ЛЛ', 'ПП', 'ВВ', 'ПП', 'ВВ', 'ЛЛ', 'ВВ', 'ПП'],
      [true, true, false, false, false, false, false, true, true, false, false, true, true, true, false, true]),
  LevelRoundFixture(2, 4, [[0, 3], [3, 2]], [],
      [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0],
      ['ВВ', 'ЛЛ', 'ВВ', 'ВВ', 'НН', 'НН', 'ЛЛ', 'ПП', 'ПП', 'НН', 'ВВ', 'ПП', 'ЛЛ', 'НН', 'ПП', 'ЛЛ'],
      [true, true, false, true, true, true, false, true, false, false, true, false, false, true, false, false]),
  LevelRoundFixture(3, 4, [[0, 2]], [[1, 1]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ВВ', 'ЛЛ', 'ЛЛ', 'ЛЛ', 'НН', 'ПП', 'НН', 'ВВ', 'НН', 'ВВ', 'ВВ', 'ПП', 'ПП', 'ПП', 'ЛЛ', 'НН'],
      [true, false, false, false, true, true, false, true, true, true, false, false, false, false, true, true]),
  LevelRoundFixture(3, 4, [[3, 1]], [[0, 1]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛЛ', 'ВВ', 'ВВ', 'ЛЛ', 'ВВ', 'ПП', 'НН', 'ПП', 'ЛЛ', 'НН', 'НН', 'ПП', 'ПП', 'ВВ', 'НН', 'ЛЛ'],
      [true, false, false, false, false, true, true, false, true, false, false, true, false, true, true, true]),
  LevelRoundFixture(3, 4, [[1, 3]], [[3, 0]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['НН', 'ПП', 'ПП', 'ВВ', 'ЛЛ', 'ПП', 'ВВ', 'ЛЛ', 'ЛЛ', 'НН', 'ЛЛ', 'НН', 'НН', 'ПП', 'ВВ', 'ВВ'],
      [false, true, false, true, true, true, false, true, false, true, false, false, false, true, true, false]),
  LevelRoundFixture(3, 4, [[3, 2]], [[1, 0]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ВВ', 'ЛЛ', 'ЛЛ', 'ПП', 'НН', 'ЛЛ', 'ЛЛ', 'ВВ', 'ПП', 'НН', 'ВВ', 'ПП', 'НН', 'ПП', 'ВВ', 'НН'],
      [true, false, false, false, true, true, false, false, true, false, true, false, true, false, true, true]),
  LevelRoundFixture(3, 4, [[0, 2]], [[3, 3]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['НН', 'ВВ', 'ВВ', 'ЛЛ', 'ВВ', 'НН', 'ПП', 'ПП', 'НН', 'ПП', 'ЛЛ', 'ПП', 'ВВ', 'НН', 'ЛЛ', 'ЛЛ'],
      [false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, false]),
  LevelRoundFixture(3, 4, [[2, 1]], [[2, 0]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛЛ', 'ВВ', 'ПП', 'ВВ', 'ПП', 'НН', 'ПП', 'ЛЛ', 'НН', 'НН', 'ВВ', 'ВВ', 'НН', 'ЛЛ', 'ПП', 'ЛЛ'],
      [true, false, true, false, false, true, false, true, false, false, true, false, true, false, true, true]),
  LevelRoundFixture(3, 4, [[2, 0]], [[0, 2]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ПП', 'ВВ', 'НН', 'ЛЛ', 'НН', 'ВВ', 'ВВ', 'ЛЛ', 'НН', 'ПП', 'ПП', 'ЛЛ', 'ЛЛ', 'ПП', 'НН', 'ВВ'],
      [false, false, true, false, false, true, false, true, false, true, false, true, false, true, true, true]),
  LevelRoundFixture(3, 4, [[3, 1]], [[1, 3]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ВВ', 'ВВ', 'НН', 'ВВ', 'НН', 'ВВ', 'ЛЛ', 'ЛЛ', 'ЛЛ', 'НН', 'ПП', 'ЛЛ', 'НН', 'ПП', 'ПП', 'ПП'],
      [false, false, true, true, true, true, true, false, false, false, true, true, false, true, false, false]),
  LevelRoundFixture(3, 4, [[2, 3]], [[0, 0]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['НН', 'ЛЛ', 'ПП', 'ЛЛ', 'ЛЛ', 'НН', 'ВВ', 'ВВ', 'ПП', 'НН', 'ПП', 'НН', 'ПП', 'ЛЛ', 'ВВ', 'ВВ'],
      [false, true, true, true, false, false, true, false, true, true, false, false, false, true, true, false]),
  LevelRoundFixture(3, 4, [[2, 0]], [[1, 0]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['НН', 'ПП', 'ВВ', 'ЛЛ', 'ЛЛ', 'ПП', 'НН', 'ПП', 'НН', 'ВВ', 'ПП', 'ЛЛ', 'ВВ', 'ВВ', 'ЛЛ', 'НН'],
      [true, false, true, true, false, true, true, false, false, true, false, true, false, false, false, true]),
  LevelRoundFixture(4, 5, [[0, 2], [1, 1]], [[4, 0]],
      [1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
      ['ПЛЛ', 'ЛЛ+Л', 'ПВВ', 'ННП', 'НЛЛ', 'ВНН', 'ППЛ', 'НВВ', 'ННН', 'ПП', 'ППВ', 'НН+Н', 'ЛВВ', 'ЛЛЛ', 'ВПП', 'НПП', 'ВВ+В', 'ПП+П', 'ННВ', 'ВВВ', 'ВВН', 'В+ВВ', 'ЛЛВ', 'ВВП'],
      [true, false, false, true, false, true, true, true, false, true, true, false, true, false, true, false, false, false, true, false, true, false, true, false]),
  LevelRoundFixture(4, 5, [[1, 1], [2, 4]], [[4, 1]],
      [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
      ['ННН', 'ПП+П', 'ВНН', 'ППЛ', 'ППВ', 'НН', 'ВВП', 'ЛЛН', 'ВПП', 'НН+Н', 'ННВ', 'В+ВВ', 'ВВЛ', 'ВВН', 'Н+НН', 'ВЛЛ', 'ЛЛВ', 'ЛЛ+Л', 'ЛПП', 'ПЛЛ', 'НЛЛ', 'ВВВ', 'ПП', 'ННЛ'],
      [true, true, false, true, false, false, false, false, false, false, false, true, false, true, false, false, true, true, true, false, true, true, true, true]),
  LevelRoundFixture(4, 5, [[0, 0], [1, 4]], [[1, 3]],
      [0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1],
      ['НЛЛ', 'ПВВ', 'ППН', 'В+ВВ', 'ВПП', 'ННВ', 'ВВП', 'Л+ЛЛ', 'ППВ', 'НН', 'ВВЛ', 'ЛЛ', 'НН+Н', 'ПЛЛ', 'ЛНН', 'ВНН', 'ПП+П', 'ЛЛП', 'ЛПП', 'ПНН', 'ЛЛ+Л', 'ННП', 'ВВ+В', 'П+ПП'],
      [false, true, true, true, false, true, false, true, false, true, false, false, false, true, false, false, true, false, true, true, true, false, false, true]),
  LevelRoundFixture(4, 5, [[2, 4], [1, 0]], [[1, 4]],
      [0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0],
      ['ННН', 'ПП+П', 'ЛВВ', 'ВВ+В', 'ПЛЛ', 'ННЛ', 'ВВВ', 'ЛНН', 'ВВП', 'ПНН', 'ПП', 'НВВ', 'ВПП', 'ВВ', 'ЛЛВ', 'ППЛ', 'ППП', 'НЛЛ', 'В+ВВ', 'ЛПП', 'ННП', 'НН', 'ЛЛН', 'ППВ'],
      [false, true, true, false, true, false, false, true, true, false, true, false, false, true, false, true, false, true, false, true, false, true, true, false]),
  LevelRoundFixture(4, 5, [[4, 1], [0, 1]], [[1, 2]],
      [0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1],
      ['ННВ', 'ЛВВ', 'ППП', 'Л+ЛЛ', 'ЛЛП', 'ЛЛ+Л', 'ВВ', 'ННЛ', 'ПП', 'ВВЛ', 'ВВП', 'ВВН', 'ЛНН', 'ППН', 'ППВ', 'ЛЛВ', 'НН+Н', 'П+ПП', 'ВЛЛ', 'ННП', 'НЛЛ', 'Н+НН', 'НВВ', 'ППЛ'],
      [true, false, false, false, false, false, false, true, true, true, true, true, true, true, false, true, true, false, false, false, false, true, true, false]),
  LevelRoundFixture(4, 5, [[1, 0], [0, 4]], [[1, 3]],
      [1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
      ['НПП', 'ВВВ', 'ЛВВ', 'ПП+П', 'ЛЛЛ', 'ПНН', 'В+ВВ', 'ПЛЛ', 'ВЛЛ', 'ЛЛП', 'ППП', 'ЛЛ+Л', 'ЛПП', 'Л+ЛЛ', 'П+ПП', 'ППЛ', 'НН', 'ВНН', 'ННН', 'НВВ', 'ВВП', 'ПВВ', 'ЛЛ', 'ВВН'],
      [false, false, false, true, false, false, true, true, false, false, true, true, true, false, false, true, true, false, true, true, false, false, true, true]),
  LevelRoundFixture(4, 5, [[0, 1], [3, 3]], [[1, 1]],
      [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1],
      ['ВВЛ', 'НН', 'ННВ', 'ВВН', 'ПНН', 'ЛНН', 'ННЛ', 'ЛЛ+Л', 'ППВ', 'ВВП', 'ЛЛН', 'Н+НН', 'ВВ+В', 'ННП', 'ВЛЛ', 'П+ПП', 'ППП', 'В+ВВ', 'НПП', 'ЛЛП', 'ЛПП', 'ППН', 'ПЛЛ', 'ВПП'],
      [true, true, true, true, true, false, false, false, false, false, true, false, false, false, false, true, true, true, false, true, true, false, true, false]),
  LevelRoundFixture(4, 5, [[0, 1], [4, 0]], [[3, 0]],
      [0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0],
      ['Л+ЛЛ', 'ЛЛП', 'ВПП', 'ПНН', 'ВВ', 'ВВ+В', 'ПВВ', 'ЛЛЛ', 'ПП', 'ННЛ', 'ННП', 'ННН', 'ВВН', 'ВЛЛ', 'НН', 'ППН', 'ППП', 'ППВ', 'НЛЛ', 'ЛНН', 'ВНН', 'НН+Н', 'ПП+П', 'ЛВВ'],
      [false, false, true, true, false, false, false, true, false, true, true, false, true, true, true, true, false, true, false, false, true, false, false, true]),
  LevelRoundFixture(4, 5, [[0, 1], [4, 4]], [[3, 3]],
      [0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
      ['В+ВВ', 'ПЛЛ', 'ПП', 'Н+НН', 'ННЛ', 'ВЛЛ', 'ПВВ', 'ННВ', 'НН', 'ЛПП', 'ННН', 'ВВВ', 'ЛВВ', 'ВВЛ', 'ВНН', 'НВВ', 'ЛЛ+Л', 'П+ПП', 'ННП', 'ППЛ', 'ЛЛЛ', 'ВПП', 'ВВП', 'НПП'],
      [false, true, true, true, false, true, true, false, true, false, false, true, true, false, true, true, false, false, false, false, false, true, false, true]),
  LevelRoundFixture(4, 5, [[1, 3], [0, 3]], [[4, 0]],
      [1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0],
      ['Л+ЛЛ', 'ЛПП', 'ПНН', 'ПП+П', 'ВВ', 'НПП', 'ЛВВ', 'ВВВ', 'ППВ', 'ННН', 'ППП', 'ВВН', 'НВВ', 'НН+Н', 'НН', 'ЛЛ+Л', 'ППЛ', 'ННЛ', 'ПВВ', 'ЛНН', 'ВВП', 'ПЛЛ', 'ППН', 'ЛЛВ'],
      [false, false, false, true, true, false, false, false, false, false, false, true, true, true, false, false, false, true, true, true, true, true, true, true]),
  LevelRoundFixture(5, 6, [[3, 3], [2, 1]], [[0, 2], [3, 5]],
      [0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0],
      ['ВВВ', 'ЛЛ+Л', 'Н+НН', 'ННП', 'НПП', 'ВПП', 'ВНН', 'ННЛ', 'ЛЛН', 'ЛЛП', 'ППЛ', 'ВВ+В', 'ПП+П', 'П+ПП', 'ЛЛЛ', 'ННВ', 'НН+Н', 'ПНН', 'НН', 'ВВН'],
      [true, false, true, false, true, false, true, false, true, false, true, true, false, false, false, true, false, false, true, true]),
  LevelRoundFixture(5, 6, [[0, 4], [0, 5]], [[2, 5], [4, 5]],
      [0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1],
      ['ННП', 'НН+Н', 'НВВ', 'НЛЛ', 'ВПП', 'ПЛЛ', 'В+ВВ', 'ППЛ', 'ВНН', 'ННЛ', 'ВЛЛ', 'ЛЛВ', 'ПВВ', 'ЛЛ+Л', 'ППН', 'ПП', 'ППП', 'ВВП', 'ЛЛЛ', 'ННН'],
      [false, false, true, false, true, false, true, true, true, false, false, true, false, false, true, true, true, false, true, false]),
  LevelRoundFixture(5, 6, [[4, 0], [3, 1]], [[2, 4], [5, 0]],
      [1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0],
      ['ННВ', 'ЛЛН', 'ПНН', 'ВПП', 'НЛЛ', 'ПВВ', 'ВВ+В', 'НН+Н', 'ВНН', 'ЛЛ', 'ННН', 'ЛЛЛ', 'ВВП', 'ВВВ', 'ППВ', 'ВВ', 'ЛЛВ', 'ЛЛП', 'Л+ЛЛ', 'ЛЛ+Л'],
      [true, true, true, true, true, false, false, false, true, true, false, false, true, false, true, false, true, false, false, false]),
  LevelRoundFixture(5, 6, [[0, 5], [3, 0]], [[1, 3], [3, 2]],
      [1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1],
      ['ННП', 'НВВ', 'ПП+П', 'ЛВВ', 'ПВВ', 'ЛЛВ', 'ППН', 'ННН', 'ЛНН', 'ПЛЛ', 'НН+Н', 'ВВЛ', 'ВВП', 'ППЛ', 'НПП', 'ННВ', 'Л+ЛЛ', 'В+ВВ', 'ЛЛ', 'НН'],
      [true, true, true, true, false, true, false, true, false, false, true, false, false, true, false, true, false, true, false, false]),
  LevelRoundFixture(5, 6, [[3, 5], [1, 3]], [[5, 4], [4, 1]],
      [0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1],
      ['ППВ', 'НН+Н', 'Л+ЛЛ', 'ВВЛ', 'ВЛЛ', 'ПВВ', 'ННВ', 'ЛЛН', 'ПП+П', 'ЛНН', 'ННЛ', 'ЛЛЛ', 'ПП', 'НВВ', 'ППЛ', 'ПЛЛ', 'ППН', 'НПП', 'ННП', 'В+ВВ'],
      [false, false, false, true, false, true, true, true, true, false, true, false, false, true, true, false, true, false, false, true]),
  LevelRoundFixture(5, 6, [[3, 0], [4, 1]], [[3, 1], [1, 5]],
      [0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0],
      ['ППЛ', 'ЛЛВ', 'ННП', 'ПП+П', 'ВВ', 'ЛЛП', 'ВВЛ', 'ПВВ', 'ЛВВ', 'ЛПП', 'ЛЛ', 'НПП', 'ВНН', 'ЛЛН', 'ПП', 'ПЛЛ', 'НН', 'ВПП', 'ПНН', 'ННЛ'],
      [true, true, true, false, false, true, true, false, false, true, true, false, false, false, false, true, true, false, true, false]),
  LevelRoundFixture(5, 6, [[2, 2], [5, 0]], [[1, 1], [5, 2]],
      [1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0],
      ['НПП', 'ЛВВ', 'ВВП', 'ЛЛП', 'ППВ', 'ВПП', 'ЛНН', 'ВНН', 'ЛЛ+Л', 'НН+Н', 'ННП', 'ПНН', 'ЛЛВ', 'ЛПП', 'ВВЛ', 'ПВВ', 'Л+ЛЛ', 'ППН', 'ВВ+В', 'Н+НН'],
      [false, false, true, true, false, false, true, true, false, true, true, false, true, false, true, true, false, true, false, false]),
  LevelRoundFixture(5, 6, [[4, 0], [3, 1]], [[3, 3], [5, 0]],
      [1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0],
      ['ВВ', 'Н+НН', 'ЛЛЛ', 'ПНН', 'ПЛЛ', 'ПВВ', 'ЛЛ+Л', 'ЛПП', 'ППП', 'ВНН', 'ЛВВ', 'ЛЛП', 'НН+Н', 'ВВЛ', 'НН', 'ВПП', 'ВВП', 'ПП', 'ВВВ', 'ННП'],
      [false, true, true, true, false, false, false, false, true, true, true, false, false, true, true, true, true, false, false, false]),
  LevelRoundFixture(5, 6, [[1, 2], [0, 0]], [[2, 1], [1, 0]],
      [1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0],
      ['ППН', 'ЛПП', 'В+ВВ', 'ВВЛ', 'ППЛ', 'ВПП', 'ЛВВ', 'ЛНН', 'ППП', 'ПЛЛ', 'ПНН', 'Н+НН', 'Л+ЛЛ', 'ЛЛЛ', 'ВВ', 'ВВН', 'ЛЛП', 'ННН', 'НПП', 'ННП'],
      [false, true, false, false, false, true, false, true, false, false, true, false, false, false, true, true, true, true, true, true]),
  LevelRoundFixture(5, 6, [[5, 3], [4, 2]], [[4, 5], [5, 2]],
      [0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1],
      ['ВНН', 'ЛНН', 'НВВ', 'ЛЛП', 'В+ВВ', 'ННН', 'Л+ЛЛ', 'ПЛЛ', 'ВВЛ', 'ПП+П', 'ПВВ', 'ЛЛН', 'ППВ', 'ПП', 'ННЛ', 'НЛЛ', 'НН+Н', 'ВВВ', 'ВВП', 'НПП'],
      [true, true, true, true, true, false, true, false, false, false, false, true, true, false, false, true, false, false, false, true]),
  LevelRoundFixture(6, 7, [[2, 1]], [[5, 1], [4, 1], [3, 1]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['НН', 'ПВВ', 'П+ПП', 'ЛПП', 'ППВ', 'ПП', 'ННН', 'ВПП', 'ННЛ', 'ЛЛ', 'ВВН', 'ПЛЛ', 'НЛЛ', 'Н+НН', 'ННВ', 'ВВЛ', 'ЛЛН', 'НН+Н', 'ЛЛВ', 'ВВ'],
      [true, false, true, true, false, false, true, false, false, true, true, true, true, false, false, true, false, false, false, true]),
  LevelRoundFixture(6, 7, [[3, 1]], [[2, 6], [5, 0], [4, 0]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ППВ', 'ВВП', 'ВЛЛ', 'ННЛ', 'ВВЛ', 'ННВ', 'ЛНН', 'ЛПП', 'ВВВ', 'ПП+П', 'ЛВВ', 'Л+ЛЛ', 'НЛЛ', 'ВНН', 'ППН', 'ВПП', 'В+ВВ', 'НН', 'ВВ+В', 'НН+Н'],
      [false, false, true, true, false, true, false, true, true, false, false, false, false, true, true, true, false, true, false, true]),
  LevelRoundFixture(6, 7, [[1, 6]], [[0, 0], [5, 2], [4, 2]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['В+ВВ', 'ВВ+В', 'НЛЛ', 'ЛЛП', 'ВВП', 'ВЛЛ', 'НН', 'ННВ', 'НПП', 'ПНН', 'ЛЛ+Л', 'ЛЛЛ', 'ЛЛН', 'Л+ЛЛ', 'ННЛ', 'НВВ', 'ННП', 'Н+НН', 'ВВН', 'ПЛЛ'],
      [true, true, false, false, false, false, true, true, true, true, true, false, false, false, false, true, false, false, true, true]),
  LevelRoundFixture(6, 7, [[1, 6]], [[1, 0], [0, 0], [4, 5]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['НПП', 'ЛЛЛ', 'ЛЛ', 'ЛЛП', 'НН', 'В+ВВ', 'Н+НН', 'ВВЛ', 'ННП', 'ПП', 'ЛНН', 'ВНН', 'НН+Н', 'ВВН', 'НВВ', 'ВВ', 'ЛПП', 'ППВ', 'ВВ+В', 'Л+ЛЛ'],
      [false, false, false, true, false, true, true, false, false, true, false, false, false, true, true, true, true, true, false, true]),
  LevelRoundFixture(6, 7, [[4, 0]], [[2, 1], [1, 3], [0, 2]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ВПП', 'ПЛЛ', 'ПВВ', 'ППЛ', 'ППВ', 'ППП', 'НВВ', 'ЛПП', 'НПП', 'ЛЛ', 'НЛЛ', 'ЛЛВ', 'ННП', 'ВВП', 'ВВ', 'ЛЛ+Л', 'ВЛЛ', 'ВВН', 'ННЛ', 'ПП+П'],
      [false, true, false, true, false, false, false, true, false, true, true, false, true, true, false, true, false, true, false, true]),
  LevelRoundFixture(6, 7, [[2, 3]], [[0, 4], [4, 4], [4, 2]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ППН', 'ННВ', 'ННЛ', 'Н+НН', 'ЛЛЛ', 'ПЛЛ', 'НПП', 'ЛЛ', 'ППП', 'ВНН', 'ВВ+В', 'ЛЛВ', 'ЛЛП', 'ВВВ', 'В+ВВ', 'ЛПП', 'ПНН', 'ПП', 'ЛЛН', 'ННН'],
      [false, true, true, false, false, true, false, false, true, false, true, true, true, false, false, true, true, false, true, false]),
  LevelRoundFixture(6, 7, [[5, 5]], [[2, 3], [2, 4], [1, 5]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛЛВ', 'ЛПП', 'ПВВ', 'ННН', 'ППП', 'Н+НН', 'ПП', 'ЛЛН', 'ВВЛ', 'ВВН', 'ЛНН', 'ПНН', 'НН+Н', 'ППН', 'ЛЛ+Л', 'ПЛЛ', 'ВВП', 'НВВ', 'ВЛЛ', 'ВВВ'],
      [true, true, true, true, false, false, false, true, false, true, false, false, false, true, true, true, false, false, false, true]),
  LevelRoundFixture(6, 7, [[1, 0]], [[0, 0], [0, 2], [6, 5]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛПП', 'ВВП', 'ЛЛ+Л', 'ППП', 'ППН', 'ПП', 'НПП', 'ПНН', 'ЛВВ', 'ВПП', 'ННП', 'ЛНН', 'ВВЛ', 'П+ПП', 'ЛЛП', 'Л+ЛЛ', 'ЛЛЛ', 'ВВ+В', 'ПП+П', 'ЛЛВ'],
      [true, false, false, true, false, false, false, true, true, false, true, true, true, false, true, false, false, false, true, true]),
  LevelRoundFixture(6, 7, [[4, 0]], [[5, 2], [1, 2], [2, 2]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ВВП', 'ВВ+В', 'ПП+П', 'ВВ', 'ВНН', 'ПНН', 'ЛПП', 'НН+Н', 'П+ПП', 'ППП', 'ЛЛВ', 'ПП', 'ПВВ', 'ЛЛ', 'ППЛ', 'ВПП', 'ЛЛП', 'ЛЛН', 'ННН', 'ННВ'],
      [false, false, false, false, true, true, true, true, false, false, true, true, false, true, true, false, true, true, false, false]),
  LevelRoundFixture(6, 7, [[2, 0]], [[6, 1], [1, 6], [0, 1]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ВВП', 'ПВВ', 'ВЛЛ', 'ЛЛН', 'ВВ', 'ЛПП', 'П+ПП', 'ВПП', 'ПНН', 'НПП', 'ННН', 'ННП', 'ВВ+В', 'В+ВВ', 'ЛЛ', 'НН', 'ННЛ', 'ВВВ', 'НЛЛ', 'ПП+П'],
      [false, false, false, false, false, true, true, false, false, false, true, false, true, false, true, true, true, true, true, true]),
  LevelRoundFixture(7, 8, [[4, 1], [4, 2]], [[2, 4], [7, 2], [7, 0]],
      [1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
      ['П+ПП', 'ЛЛЛ+Л', 'Л+ЛЛ', 'ВНН', 'ПЛЛ', 'ВЛЛ', 'ВЛЛЛ', 'Н+НН', 'ННП', 'ННЛ', 'ППЛ', 'ЛПП', 'НН', 'ПНН', 'ЛВВ', 'ЛНН', 'ЛЛВ', 'ЛЛЛ', 'НВВВ', 'В+ВВ', 'ЛППП', 'ПЛЛЛ', 'НЛЛ', 'ВВП', 'ЛВВВ', 'ННПП', 'Л+ЛЛЛ', 'П+ППП', 'ЛЛВВ', 'ВВ+В', 'ВВВП', 'ПП', 'ВВВ', 'ВВ', 'НППП', 'ППВВ', 'ЛЛНН', 'ПННН', 'ЛЛ+ЛЛ', 'Н+ННН', 'НН+Н', 'ВВЛ', 'ННН', 'ВВВН', 'НННН', 'НННП', 'ННН+Н', 'ПВВВ'],
      [false, true, true, true, false, false, false, true, true, false, true, true, false, false, true, false, false, true, true, false, true, true, false, true, false, true, false, true, true, true, false, true, false, false, true, false, true, true, false, true, false, true, false, false, true, false, false, false]),
  LevelRoundFixture(7, 8, [[1, 7], [1, 4]], [[7, 2], [5, 0], [0, 3]],
      [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
      ['П+ПП', 'ПЛЛ', 'НВВВ', 'ВВВЛ', 'ППЛ', 'В+ВВВ', 'НННН', 'ЛВВВ', 'ЛЛНН', 'ПППВ', 'ВЛЛ', 'ВВН', 'ЛЛВВ', 'ЛННН', 'ННП', 'ППН', 'ВВ+ВВ', 'ВВВН', 'ЛЛ+Л', 'ЛЛЛН', 'ЛПП', 'ВВВ+В', 'ВННН', 'ПППЛ', 'НЛЛ', 'ПП+ПП', 'ЛЛ', 'ВППП', 'НЛЛЛ', 'ППНН', 'НН', 'ПНН', 'ПП+П', 'ПННН', 'ВВПП', 'ННПП', 'ППВ', 'ВВЛ', 'ВВ+В', 'ЛЛВ', 'ВВВВ', 'НННП', 'ЛЛ+ЛЛ', 'ПП', 'Н+НН', 'ЛЛЛВ', 'НН+Н', 'Н+ННН'],
      [true, true, true, false, true, true, false, true, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, false, false, false, true, false, true, true, true, false, false, false, true, true, true, true, false]),
  LevelRoundFixture(7, 8, [[3, 1], [2, 6]], [[1, 1], [7, 0], [1, 5]],
      [0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
      ['ЛЛН', 'ННН+Н', 'ВНН', 'ПП+П', 'ЛЛВ', 'НВВВ', 'Л+ЛЛ', 'НННВ', 'ВННН', 'ЛЛ', 'ВВВП', 'ВЛЛ', 'ВВЛ', 'ЛЛЛ', 'ПППН', 'ЛВВ', 'ПВВ', 'ВВ', 'ПП', 'ЛЛЛП', 'ПП+ПП', 'ВВН', 'НЛЛ', 'ЛЛ+ЛЛ', 'ННЛЛ', 'П+ПП', 'ЛЛВВ', 'ПЛЛЛ', 'ВЛЛЛ', 'ЛЛЛН', 'ПППП', 'ЛННН', 'НЛЛЛ', 'ВВ+В', 'Л+ЛЛЛ', 'ВВВЛ', 'НВВ', 'ЛЛП', 'Н+ННН', 'В+ВВВ', 'ЛНН', 'ВВ+ВВ', 'ВВВ+В', 'ЛПП', 'ВВЛЛ', 'НПП', 'ННЛ', 'НННЛ'],
      [true, false, true, true, true, false, true, false, false, false, true, false, true, false, true, true, true, false, true, false, false, false, true, false, true, true, false, false, true, false, true, false, false, false, true, false, false, true, true, false, false, true, false, true, false, true, true, true]),
  LevelRoundFixture(7, 8, [[3, 4], [4, 5]], [[1, 6], [7, 1], [3, 1]],
      [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1],
      ['ПВВВ', 'ПППЛ', 'ННВ', 'НН+Н', 'Н+ННН', 'ПП+ПП', 'ППВВ', 'НН+НН', 'ПВВ', 'ВВ', 'ННН+Н', 'ПППВ', 'ВВП', 'ПППП', 'ППВ', 'НПП', 'НЛЛЛ', 'ННП', 'НН', 'ВЛЛЛ', 'ПЛЛ', 'Н+НН', 'НВВВ', 'П+ПП', 'ВВВВ', 'ПЛЛЛ', 'ЛЛН', 'ЛВВ', 'ПП', 'ВЛЛ', 'ЛЛВ', 'ЛЛЛ', 'В+ВВВ', 'ЛЛЛЛ', 'ЛННН', 'ЛЛНН', 'ЛЛВВ', 'ННН', 'ВВ+ВВ', 'ЛЛЛН', 'ЛВВВ', 'ВВЛЛ', 'ПНН', 'ПППН', 'НЛЛ', 'НННВ', 'ВВЛ', 'ЛНН'],
      [true, true, true, true, false, false, false, false, true, false, false, true, false, false, false, false, true, false, true, false, true, false, true, false, false, true, true, true, true, false, true, false, false, true, false, false, false, true, true, false, false, false, true, true, true, true, true, true]),
  LevelRoundFixture(7, 8, [[5, 2], [6, 0]], [[3, 0], [0, 2], [7, 7]],
      [0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0],
      ['ЛЛЛЛ', 'ВППП', 'ППП+П', 'ПП+П', 'ВВЛ', 'Н+НН', 'П+ПП', 'НН+НН', 'ВВП', 'ПППЛ', 'ЛЛ', 'ЛЛП', 'ВВВН', 'ЛВВВ', 'ПП+ПП', 'ВВПП', 'В+ВВ', 'ЛЛНН', 'ННЛ', 'ЛВВ', 'ННЛЛ', 'НЛЛЛ', 'Л+ЛЛЛ', 'ВЛЛЛ', 'ЛЛН', 'ЛНН', 'ППН', 'НЛЛ', 'ЛЛЛ+Л', 'ЛЛ+Л', 'ЛППП', 'ННН', 'ЛЛ+ЛЛ', 'НН+Н', 'НВВВ', 'ВННН', 'ННПП', 'ПНН', 'ПППВ', 'ВЛЛ', 'ВВ+В', 'ПППН', 'Л+ЛЛ', 'ЛЛВВ', 'ВВВ', 'ПВВ', 'НННП', 'ВВ'],
      [true, true, false, true, false, true, false, false, false, false, true, false, true, false, false, false, false, true, true, true, false, false, false, false, false, true, true, true, false, false, true, true, true, false, true, true, true, false, true, true, true, false, false, false, true, true, true, false]),
  LevelRoundFixture(7, 8, [[3, 1], [7, 3]], [[0, 5], [5, 4], [1, 5]],
      [1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1],
      ['ВВВВ', 'ПНН', 'НН', 'ЛЛЛВ', 'ППВВ', 'ВВП', 'ППВ', 'ВЛЛ', 'ВВВ', 'ЛЛВВ', 'ЛЛН', 'ВННН', 'ВПП', 'НЛЛЛ', 'ЛППП', 'ЛЛП', 'НВВВ', 'ЛЛЛЛ', 'ЛЛВ', 'ВВ+ВВ', 'ППП', 'Л+ЛЛЛ', 'ННН+Н', 'ПППЛ', 'ННЛ', 'ВППП', 'ЛВВВ', 'ЛЛЛ', 'Л+ЛЛ', 'ПЛЛЛ', 'ННВ', 'ЛНН', 'ЛЛЛ+Л', 'ПППВ', 'ННПП', 'ВВПП', 'НННВ', 'ПППП', 'ППЛ', 'НН+НН', 'ПП+ПП', 'Н+ННН', 'ПВВ', 'ПППН', 'ВЛЛЛ', 'ПП+П', 'НВВ', 'ЛЛ+Л'],
      [false, false, true, true, true, false, false, false, true, false, true, true, false, true, true, true, false, false, true, false, true, false, true, true, false, false, false, false, false, true, false, false, true, true, true, true, true, false, true, true, false, false, false, true, true, false, true, false]),
  LevelRoundFixture(7, 8, [[6, 4], [5, 6]], [[0, 2], [5, 2], [1, 7]],
      [0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1],
      ['ВВВ+В', 'ЛНН', 'ННН+Н', 'НН+Н', 'ЛВВ', 'ВВВН', 'ПЛЛЛ', 'ВВВП', 'ПЛЛ', 'НННЛ', 'ПППП', 'ВВН', 'ППН', 'ВВ+В', 'Л+ЛЛЛ', 'ПП+ПП', 'ЛЛЛП', 'ЛЛ', 'В+ВВ', 'ПППН', 'ППВ', 'НВВ', 'ВЛЛЛ', 'ВВПП', 'ЛЛ+Л', 'П+ППП', 'ВННН', 'ВВВЛ', 'НН', 'ЛЛЛН', 'ПНН', 'ПП+П', 'ВППП', 'ЛППП', 'ЛЛЛ+Л', 'НННП', 'Н+НН', 'ППП', 'ВЛЛ', 'Н+ННН', 'ППВВ', 'ЛЛП', 'ННН', 'ПП', 'Л+ЛЛ', 'ННЛ', 'ПННН', 'ННПП'],
      [true, false, false, false, false, true, true, false, true, true, true, true, true, true, true, false, true, true, false, false, true, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, true, true, true, true, true, false, false, true, true, false, true]),
  LevelRoundFixture(7, 8, [[4, 7], [2, 6]], [[3, 4], [1, 5], [6, 1]],
      [1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
      ['ВНН', 'ЛЛН', 'ЛЛ+ЛЛ', 'ЛЛЛ+Л', 'ВННН', 'ЛЛП', 'ПППН', 'ПВВ', 'ВВ+ВВ', 'ВВВВ', 'ННН', 'ВВВП', 'П+ППП', 'ППВ', 'ВПП', 'ПППВ', 'ВВПП', 'ВВП', 'Н+ННН', 'В+ВВ', 'ННЛЛ', 'ЛППП', 'ППН', 'НН+Н', 'ПП', 'ЛЛ+Л', 'ПППП', 'ВВ+В', 'ПВВВ', 'ЛЛЛЛ', 'ВЛЛЛ', 'ЛЛЛВ', 'ННЛ', 'ПППЛ', 'ВВ', 'ВВВН', 'НЛЛ', 'ПЛЛ', 'ЛЛЛН', 'ВВН', 'ВВВ+В', 'НППП', 'НННП', 'ППВВ', 'ЛЛВВ', 'ЛПП', 'ННПП', 'ПП+ПП'],
      [true, false, true, false, false, false, false, false, true, true, true, true, true, false, true, false, false, true, true, false, false, false, false, true, false, true, false, true, true, false, true, false, true, true, true, false, false, true, false, true, false, true, true, false, true, true, false, false]),
  LevelRoundFixture(7, 8, [[1, 4], [4, 3]], [[4, 7], [4, 4], [1, 3]],
      [0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0],
      ['ВВЛЛ', 'ЛЛЛВ', 'ЛЛЛН', 'Л+ЛЛЛ', 'ВВН', 'В+ВВВ', 'ВЛЛ', 'Л+ЛЛ', 'ЛЛЛП', 'ЛЛ', 'ЛЛ+ЛЛ', 'ПП+ПП', 'ЛЛ+Л', 'ВВ+ВВ', 'ЛПП', 'Н+НН', 'ППП', 'ППВВ', 'П+ППП', 'НН+НН', 'ПП+П', 'ВПП', 'В+ВВ', 'ННН', 'ВВП', 'ПП', 'ЛЛЛ+Л', 'ННЛЛ', 'ВНН', 'ЛЛЛЛ', 'ЛЛНН', 'НЛЛЛ', 'ВВЛ', 'ППНН', 'ВВВН', 'ЛНН', 'ЛЛЛ', 'НВВВ', 'ВВВ+В', 'НННВ', 'ЛЛВВ', 'НЛЛ', 'ППН', 'ППВ', 'ПННН', 'ВВВЛ', 'ВЛЛЛ', 'ЛННН'],
      [false, true, false, false, false, true, false, false, false, false, false, true, false, false, true, false, true, false, false, false, false, false, false, true, true, true, true, true, true, true, true, false, false, true, true, true, false, true, true, true, false, false, true, true, true, true, false, true]),
  LevelRoundFixture(7, 8, [[4, 7], [3, 0]], [[1, 6], [2, 2], [0, 4]],
      [0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0],
      ['ННП', 'ППВВ', 'НЛЛЛ', 'ВВ+ВВ', 'ЛЛ+ЛЛ', 'ЛЛ', 'ПВВ', 'ННЛ', 'НВВВ', 'ВВ', 'ПППП', 'ЛЛЛ', 'ПППВ', 'НН+Н', 'НН+НН', 'ПП', 'ЛНН', 'ВПП', 'ППНН', 'ВЛЛЛ', 'ЛННН', 'ННЛЛ', 'ППП', 'ПНН', 'ЛПП', 'ПП+П', 'ПВВВ', 'ВНН', 'НННВ', 'П+ППП', 'В+ВВ', 'ВВН', 'ННПП', 'ЛВВ', 'НННЛ', 'ННН', 'НННП', 'НННН', 'ВВВЛ', 'ННВ', 'ВВВ', 'ВВВВ', 'ВЛЛ', 'ЛЛВВ', 'Л+ЛЛ', 'ННН+Н', 'ЛЛЛН', 'ВВЛЛ'],
      [false, false, true, true, false, true, true, true, false, true, true, false, false, true, false, true, true, true, true, true, true, true, false, false, false, false, true, true, false, false, true, true, false, false, true, false, false, true, false, true, true, true, false, false, false, false, false, false]),
  LevelRoundFixture(8, 9, [[8, 0]], [[7, 5], [5, 0], [1, 0], [0, 3]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛПП', 'ПВВВ', 'ЛЛЛ+Л', 'ППВВ', 'ВВВП', 'ЛЛН', 'ПП+П', 'ПППВ', 'НННП', 'ППН', 'ВВВВ', 'ЛЛНН', 'ПП', 'ВВП', 'ВНН', 'ЛЛ', 'НННВ', 'ПННН', 'Л+ЛЛЛ', 'Н+НН', 'НЛЛ', 'П+ППП', 'ВННН', 'ПППН', 'НВВ', 'ПНН', 'ЛННН', 'ППЛ'],
      [false, false, true, false, false, true, true, true, false, false, false, true, true, false, true, true, true, true, true, false, false, true, false, false, true, false, false, true]),
  LevelRoundFixture(8, 9, [[7, 5]], [[8, 8], [2, 5], [5, 2], [2, 7]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['НННВ', 'ННВ', 'НЛЛЛ', 'ППВВ', 'ЛЛВВ', 'П+ППП', 'ППВ', 'ПППВ', 'ПП+ПП', 'ППН', 'ВННН', 'НЛЛ', 'ППП', 'ННН+Н', 'ЛЛНН', 'ВВН', 'ПВВВ', 'Н+НН', 'ЛННН', 'ПЛЛ', 'ВВВ', 'ЛЛЛЛ', 'ПППН', 'ННЛЛ', 'ПЛЛЛ', 'НН+Н', 'ННН', 'ЛЛЛН'],
      [true, true, false, false, true, false, true, false, false, false, true, true, false, false, false, true, true, true, false, true, true, true, true, false, false, true, false, false]),
  LevelRoundFixture(8, 9, [[5, 0]], [[6, 0], [5, 8], [7, 6], [7, 5]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛЛ', 'ЛВВ', 'НВВВ', 'ВВН', 'ВВВВ', 'НННЛ', 'Л+ЛЛЛ', 'ЛППП', 'ЛЛЛН', 'ЛЛЛ', 'ВВЛ', 'ВЛЛЛ', 'ППВ', 'ЛПП', 'ВВ', 'П+ПП', 'ННВ', 'НННП', 'В+ВВ', 'НВВ', 'ВВЛЛ', 'ЛЛВВ', 'П+ППП', 'ВВВЛ', 'ННН', 'НЛЛ', 'ВВВН', 'ЛЛНН'],
      [true, false, false, false, false, true, false, true, true, false, true, false, true, true, false, true, true, false, false, true, false, false, false, false, true, true, true, true]),
  LevelRoundFixture(8, 9, [[3, 0]], [[2, 2], [3, 7], [1, 5], [7, 6]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛЛЛВ', 'ЛЛЛП', 'В+ВВВ', 'ВПП', 'В+ВВ', 'ПЛЛ', 'ЛЛН', 'НН+НН', 'НЛЛ', 'ВВ+ВВ', 'ПВВ', 'Н+ННН', 'ВЛЛЛ', 'ЛЛВВ', 'НВВ', 'ВВП', 'ВВН', 'НННН', 'ННП', 'ПП+ПП', 'ЛЛП', 'ННВ', 'П+ППП', 'НПП', 'НННП', 'ВВ', 'НННВ', 'ЛНН'],
      [false, true, false, false, false, true, false, true, false, true, false, true, false, false, true, true, true, true, true, true, true, true, false, true, false, false, false, false]),
  LevelRoundFixture(8, 9, [[2, 8]], [[7, 6], [7, 2], [2, 4], [5, 8]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ВВВЛ', 'ЛЛЛВ', 'ПННН', 'П+ПП', 'НППП', 'НННЛ', 'ННПП', 'ВВЛЛ', 'ПП+ПП', 'ЛЛП', 'ППНН', 'П+ППП', 'НЛЛ', 'НН', 'ППВ', 'ЛЛ', 'НЛЛЛ', 'НННН', 'ПП+П', 'ЛЛВВ', 'Л+ЛЛ', 'ВВН', 'Н+ННН', 'НННВ', 'ЛЛНН', 'ВВВП', 'ПП', 'ВЛЛ'],
      [true, false, true, false, false, false, false, true, true, true, false, false, true, false, true, true, false, false, true, false, true, true, false, true, false, false, true, true]),
  LevelRoundFixture(8, 9, [[5, 2]], [[7, 2], [8, 1], [7, 6], [0, 7]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['НППП', 'ПП', 'ННН+Н', 'НЛЛЛ', 'ВВВВ', 'ПППП', 'ВЛЛ', 'ППП', 'ЛЛНН', 'П+ПП', 'ПППВ', 'ВВ+В', 'ВВП', 'ВВВ+В', 'ВПП', 'ВВВП', 'ПНН', 'ПВВВ', 'Н+НН', 'ППВВ', 'ВВПП', 'ППЛ', 'ЛЛЛП', 'Л+ЛЛ', 'ННЛЛ', 'НН', 'ННПП', 'ЛППП'],
      [true, false, true, true, true, false, true, true, true, true, false, false, true, false, false, false, false, false, true, false, false, false, true, true, true, false, false, true]),
  LevelRoundFixture(8, 9, [[8, 5]], [[6, 8], [6, 0], [6, 6], [2, 7]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['Н+ННН', 'П+ППП', 'ПНН', 'ППП+П', 'НННП', 'ПННН', 'ВВПП', 'ЛЛ+Л', 'НВВВ', 'ВЛЛ', 'НВВ', 'ЛЛЛН', 'ЛНН', 'ППВВ', 'ВВВ', 'ППВ', 'НННН', 'Н+НН', 'ННЛ', 'ЛВВ', 'ППП', 'ННЛЛ', 'ПППН', 'ВВН', 'ЛЛН', 'Л+ЛЛ', 'ВВЛЛ', 'ЛННН'],
      [false, false, false, false, false, false, false, true, true, true, true, true, false, true, false, false, true, false, true, true, true, true, true, true, false, true, false, false]),
  LevelRoundFixture(8, 9, [[8, 5]], [[1, 4], [5, 8], [5, 6], [7, 6]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛЛЛП', 'ВВВЛ', 'ВПП', 'НН', 'В+ВВВ', 'ВВВ', 'ЛВВ', 'НВВ', 'ППНН', 'ППВВ', 'ПППП', 'ПЛЛЛ', 'ВВВ+В', 'ППП+П', 'ПППВ', 'ВНН', 'НН+НН', 'ЛЛЛ+Л', 'НН+Н', 'ВВВН', 'Н+НН', 'ННЛЛ', 'ПННН', 'ВЛЛ', 'Л+ЛЛ', 'В+ВВ', 'НННВ', 'ВВЛ'],
      [true, true, true, true, false, true, false, false, false, false, false, true, false, false, false, true, true, true, true, true, false, false, false, false, false, true, true, true]),
  LevelRoundFixture(8, 9, [[0, 2]], [[5, 8], [4, 0], [0, 5], [6, 1]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛВВ', 'ППНН', 'ПЛЛЛ', 'ЛЛ', 'ППП+П', 'ВЛЛЛ', 'НН+НН', 'НЛЛЛ', 'ЛЛ+ЛЛ', 'ВВВН', 'ЛЛН', 'ЛЛ+Л', 'ВВ+ВВ', 'ЛННН', 'ВВВВ', 'Л+ЛЛ', 'ЛЛВ', 'ВППП', 'ЛЛЛН', 'ЛЛЛ', 'ПП+П', 'ННВ', 'ВВЛ', 'НННВ', 'ППВ', 'ВВ', 'ВВВП', 'В+ВВВ'],
      [false, true, true, false, true, true, true, false, false, true, false, false, true, true, true, false, false, false, false, false, true, true, false, true, true, true, false, false]),
  LevelRoundFixture(8, 9, [[5, 8]], [[0, 0], [2, 3], [3, 4], [8, 4]],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      ['ЛПП', 'ННП', 'ПЛЛЛ', 'ЛЛ+Л', 'ВВП', 'ПП', 'НН+НН', 'ПП+ПП', 'ВНН', 'ЛЛЛ', 'ННН', 'ПППВ', 'ППВ', 'ППВВ', 'П+ПП', 'ННН+Н', 'ННПП', 'П+ППП', 'ПЛЛ', 'Н+ННН', 'НВВ', 'ЛЛЛВ', 'ЛЛ+ЛЛ', 'ЛЛНН', 'ПВВВ', 'ВВ+ВВ', 'ВВВ+В', 'ВВЛ'],
      [true, false, true, true, true, true, false, true, true, true, false, true, false, false, false, false, false, false, true, false, true, true, true, false, true, false, false, false]),
  LevelRoundFixture(9, 9, [[6, 0], [8, 6]], [[5, 5], [3, 8], [5, 6], [6, 8], [5, 1]],
      [1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
      ['ППНН', 'НННП', 'ВППП', 'ЛЛЛ', 'НВВВ', 'Л+ЛЛ', 'ППН', 'ПНН', 'ЛЛЛВ', 'ННП', 'ВВВ', 'ВВ', 'ПППЛ', 'ЛЛ+Л', 'ВВ+ВВ', 'В+ВВВ', 'ВНН', 'ЛЛП', 'ННН+Н', 'НВВ', 'ПВВВ', 'ЛЛЛ+Л', 'ПП', 'НН', 'Н+ННН', 'ЛЛ', 'ВВВП', 'ЛППП'],
      [false, true, false, true, true, false, true, false, false, false, true, true, false, true, false, false, true, true, true, true, false, false, false, true, false, true, false, true]),
  LevelRoundFixture(9, 9, [[0, 5], [4, 4]], [[5, 2], [1, 5], [2, 3], [1, 8], [7, 7]],
      [0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
      ['ЛЛП', 'ЛЛНН', 'ПВВВ', 'ВВВВ', 'ВЛЛЛ', 'ППП', 'В+ВВВ', 'НВВВ', 'Н+ННН', 'ПППП', 'НН+Н', 'ПЛЛЛ', 'НВВ', 'ВВ', 'ПП+П', 'ЛЛЛЛ', 'ЛЛЛП', 'ВВП', 'П+ППП', 'ППЛ', 'ПП+ПП', 'ПННН', 'ЛЛЛ', 'Л+ЛЛ', 'ЛЛВВ', 'ПППЛ', 'ВЛЛ', 'Н+НН'],
      [false, true, true, true, false, true, false, false, true, true, false, true, true, false, false, false, false, true, false, true, false, true, true, false, false, false, true, true]),
  LevelRoundFixture(9, 9, [[7, 4], [3, 4]], [[3, 1], [1, 2], [0, 2], [0, 5], [5, 2]],
      [1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
      ['ЛЛНН', 'ЛЛ+Л', 'ПВВВ', 'ЛВВВ', 'Л+ЛЛЛ', 'Л+ЛЛ', 'ППВ', 'ВВВЛ', 'ППВВ', 'ВВВ+В', 'ПППП', 'ННН+Н', 'ПП+П', 'ЛППП', 'ЛНН', 'ПП+ПП', 'ННВ', 'ПППВ', 'НН+Н', 'ННЛ', 'ННЛЛ', 'ЛННН', 'ЛЛ+ЛЛ', 'НННВ', 'В+ВВВ', 'Н+НН', 'НППП', 'ВВП'],
      [true, false, true, false, false, false, false, true, true, false, false, true, true, false, true, false, false, true, true, false, false, false, true, false, true, true, true, true]),
  LevelRoundFixture(9, 9, [[8, 6], [2, 7]], [[4, 7], [5, 2], [4, 4], [2, 3], [0, 6]],
      [0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1],
      ['ВВВ', 'ННВ', 'ЛППП', 'Л+ЛЛЛ', 'ВВ+ВВ', 'ПНН', 'ЛЛЛН', 'НННЛ', 'ПЛЛЛ', 'НЛЛЛ', 'ВВН', 'ПЛЛ', 'ВННН', 'ВВПП', 'НВВ', 'ПППЛ', 'ЛЛЛЛ', 'П+ППП', 'Л+ЛЛ', 'ПВВВ', 'ПППВ', 'ППВ', 'ЛЛ+Л', 'НННН', 'ПППП', 'ВВЛ', 'ПВВ', 'ППВВ'],
      [true, true, false, false, false, false, true, true, true, false, false, true, false, true, true, true, false, true, false, true, true, false, false, false, false, true, true, false]),
  LevelRoundFixture(9, 9, [[5, 4], [3, 5]], [[1, 6], [7, 2], [5, 2], [3, 1], [8, 6]],
      [0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
      ['ННЛ', 'НННН', 'ННН', 'ПППП', 'НННЛ', 'П+ППП', 'ЛПП', 'ППП', 'ННВ', 'ННН+Н', 'ВВ+В', 'ВВВЛ', 'ПП+П', 'ВВВП', 'ВНН', 'ППЛ', 'ЛВВВ', 'ЛЛ+ЛЛ', 'ЛЛНН', 'ЛННН', 'ПППН', 'ВВ+ВВ', 'НВВВ', 'ВВЛ', 'ННПП', 'ПВВ', 'ЛЛ', 'Н+ННН'],
      [true, false, false, true, false, false, true, false, true, false, true, false, false, true, false, true, false, true, true, true, true, true, false, false, false, true, true, false]),
  LevelRoundFixture(9, 9, [[7, 4], [0, 4]], [[4, 7], [0, 7], [0, 3], [3, 7], [8, 7]],
      [1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1],
      ['ННЛ', 'ЛЛП', 'ПННН', 'НННН', 'ВВ+В', 'НПП', 'ВВПП', 'ННП', 'НННП', 'ВПП', 'НННВ', 'НППП', 'Л+ЛЛЛ', 'ННН', 'НННЛ', 'ПППН', 'НЛЛЛ', 'Н+НН', 'ВНН', 'ПП+ПП', 'ЛЛЛЛ', 'ЛППП', 'ВВН', 'П+ППП', 'ЛЛН', 'ВВЛЛ', 'ЛЛ', 'Л+ЛЛ'],
      [false, true, true, true, true, false, true, true, false, true, false, true, true, true, false, false, false, false, false, false, false, false, true, false, false, true, true, true]),
  LevelRoundFixture(9, 9, [[4, 4], [7, 5]], [[2, 1], [8, 5], [2, 4], [1, 0], [7, 8]],
      [0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1],
      ['ППВ', 'НЛЛЛ', 'ППВВ', 'ЛЛЛ+Л', 'ЛЛ+Л', 'ПППП', 'НЛЛ', 'НН+НН', 'ВВВЛ', 'ННН+Н', 'ННЛ', 'ВВВН', 'НПП', 'ННВ', 'ПП+ПП', 'ППП+П', 'ННП', 'ПНН', 'Н+ННН', 'ПППЛ', 'НННН', 'ЛВВ', 'ЛЛП', 'ПЛЛЛ', 'ВВН', 'ВННН', 'ВППП', 'НППП'],
      [true, true, true, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, false, false, true, false, true, true, true, true, false]),
  LevelRoundFixture(9, 9, [[3, 0], [7, 8]], [[7, 4], [6, 4], [8, 2], [8, 0], [4, 2]],
      [1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
      ['НННН', 'ВВЛЛ', 'ЛЛЛ+Л', 'Л+ЛЛ', 'ЛВВ', 'ВВПП', 'НППП', 'ПЛЛ', 'ВЛЛ', 'ВВ', 'ПППВ', 'ВВ+В', 'ВВВ+В', 'ВВЛ', 'ННН', 'ЛЛ', 'П+ПП', 'ПП+П', 'ЛЛЛ', 'ВВВП', 'ВВВЛ', 'ПВВ', 'НЛЛЛ', 'НННЛ', 'ПВВВ', 'ВЛЛЛ', 'ННВ', 'ВППП'],
      [false, true, true, false, false, true, true, true, true, false, false, true, false, false, true, false, true, false, true, false, true, false, false, true, false, true, true, false]),
  LevelRoundFixture(9, 9, [[2, 5], [6, 8]], [[1, 4], [1, 3], [2, 8], [2, 1], [5, 7]],
      [0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1],
      ['ПППН', 'ЛЛ+Л', 'ЛПП', 'ЛЛЛ+Л', 'ПЛЛЛ', 'ЛЛ', 'ННЛ', 'ЛННН', 'ВВ+ВВ', 'НН+Н', 'ПППВ', 'ВВВВ', 'ЛЛЛН', 'ППЛ', 'ППВ', 'ЛЛН', 'ППНН', 'П+ППП', 'Н+ННН', 'ВЛЛЛ', 'ЛППП', 'ВВВП', 'ПНН', 'В+ВВ', 'ЛЛНН', 'ПВВ', 'ВНН', 'ВННН'],
      [true, true, true, false, true, true, true, false, true, false, true, false, true, false, true, true, false, true, false, false, true, true, false, false, false, false, false, false]),
  LevelRoundFixture(9, 9, [[6, 2], [8, 8]], [[3, 4], [3, 6], [8, 4], [0, 3], [3, 1]],
      [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1],
      ['ПППН', 'ЛППП', 'ЛЛВ', 'ВВ+ВВ', 'ПП+П', 'ЛЛН', 'ППН', 'НННП', 'ВВЛ', 'ВВЛЛ', 'НЛЛ', 'ЛВВ', 'ВВВП', 'ПВВВ', 'ПП+ПП', 'ЛЛНН', 'ЛВВВ', 'ВПП', 'ПЛЛ', 'НН+НН', 'ЛЛ+ЛЛ', 'НН', 'НН+Н', 'В+ВВВ', 'ПППВ', 'П+ПП', 'НННН', 'ВВП'],
      [false, true, true, false, false, true, false, true, true, true, false, false, false, false, false, false, true, false, true, false, false, true, true, true, false, true, true, true]),
  LevelRoundFixture(10, 10, [[1, 4], [4, 5]], [[3, 9], [8, 9], [2, 0], [7, 5], [7, 3], [4, 8]],
      [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0],
      ['ЛЛЛЛ', 'ППВВ', 'ННН+Н', 'ПППВ', 'НПП', 'ВВЛ', 'ВВП', 'НННН', 'ЛЛВВ', 'ППП+П', 'ЛННН', 'ПП+П', 'ППНН', 'НППП', 'ННВ', 'ЛЛ+ЛЛ', 'ЛПП', 'ПППЛ', 'ЛЛЛ+Л', 'ПЛЛ', 'ЛЛЛН', 'НН+НН', 'ПП+ПП', 'ПЛЛЛ', 'ННП', 'НН', 'Н+НН', 'НННП'],
      [false, true, true, true, false, true, true, true, false, false, true, false, true, false, true, false, false, false, true, true, false, false, true, true, true, false, false, false]),
  LevelRoundFixture(10, 10, [[7, 9], [7, 6]], [[0, 1], [6, 7], [3, 2], [5, 3], [4, 4], [7, 5]],
      [1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
      ['ЛВВ', 'ПННН', 'НВВВ', 'ЛЛЛП', 'НН', 'ПППЛ', 'ВВЛ', 'ПЛЛЛ', 'Л+ЛЛЛ', 'ЛННН', 'ПППП', 'ВВН', 'ЛЛН', 'ПППВ', 'ВВВП', 'НППП', 'ВВВ+В', 'ЛЛЛ+Л', 'ЛЛ', 'НННП', 'ППВ', 'ЛЛЛЛ', 'ВПП', 'НЛЛЛ', 'ННВ', 'ППП', 'ЛЛП', 'ВВВЛ'],
      [true, false, true, true, false, true, true, true, true, false, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, true, true, true]),
  LevelRoundFixture(10, 10, [[4, 5], [3, 5]], [[2, 7], [7, 1], [8, 2], [3, 3], [9, 8], [2, 3]],
      [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0],
      ['ВВВН', 'ННЛЛ', 'ЛЛП', 'ННВ', 'ЛЛВ', 'ЛЛ+ЛЛ', 'ПППП', 'НННН', 'ННП', 'НПП', 'ППВ', 'В+ВВ', 'ВВВ+В', 'ВВ+В', 'ННПП', 'ЛППП', 'ЛВВ', 'НЛЛЛ', 'ВППП', 'ППП', 'Н+ННН', 'Л+ЛЛЛ', 'ВВЛЛ', 'ВВН', 'НППП', 'ВПП', 'ПННН', 'ЛЛН'],
      [false, false, false, true, true, false, true, false, false, false, false, true, true, false, true, false, true, true, false, true, true, false, true, true, false, false, true, true]),
  LevelRoundFixture(10, 10, [[7, 8], [6, 8]], [[4, 8], [5, 9], [8, 4], [9, 8], [4, 5], [2, 2]],
      [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1],
      ['НННН', 'ВВПП', 'В+ВВ', 'ПЛЛЛ', 'ЛЛ+Л', 'Л+ЛЛЛ', 'ЛЛЛП', 'НПП', 'ППНН', 'ННП', 'ПЛЛ', 'НН+НН', 'ППЛ', 'ВЛЛЛ', 'ННПП', 'ЛЛ+ЛЛ', 'НЛЛЛ', 'П+ПП', 'ПППЛ', 'ПННН', 'Н+НН', 'ЛЛЛ', 'ЛЛНН', 'ВВВ+В', 'ЛЛЛ+Л', 'ПППН', 'ПНН', 'ЛЛ'],
      [false, true, true, false, true, true, true, true, false, false, true, false, true, true, true, false, false, true, false, false, true, false, false, true, false, false, false, true]),
  LevelRoundFixture(10, 10, [[8, 0], [6, 3]], [[5, 3], [1, 0], [7, 4], [4, 9], [1, 2], [0, 6]],
      [1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1],
      ['ВЛЛ', 'ННПП', 'ЛЛВВ', 'ПП+П', 'Л+ЛЛЛ', 'ППЛ', 'ЛЛ+ЛЛ', 'НННП', 'ПВВВ', 'НВВВ', 'ППВ', 'П+ПП', 'ППН', 'ВПП', 'ПЛЛЛ', 'НННН', 'ЛЛЛ', 'НПП', 'ННН', 'В+ВВ', 'П+ППП', 'ННВ', 'ВВПП', 'ЛПП', 'ВВЛ', 'ПППП', 'ЛППП', 'ЛННН'],
      [true, false, false, false, true, false, false, true, false, true, false, false, false, false, true, false, true, true, true, false, true, true, true, true, false, true, false, true]),
  LevelRoundFixture(10, 10, [[4, 0], [6, 7]], [[8, 9], [8, 4], [5, 6], [5, 2], [4, 9], [6, 4]],
      [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1],
      ['ВЛЛ', 'ВВЛ', 'ВВП', 'ЛЛВ', 'ВВВН', 'ВЛЛЛ', 'ЛЛЛ+Л', 'ННП', 'ППВВ', 'ППВ', 'ПП+ПП', 'ВВ+ВВ', 'Л+ЛЛЛ', 'ППЛ', 'ЛЛ+Л', 'НН+НН', 'НННП', 'НННЛ', 'В+ВВ', 'ННЛ', 'ЛЛЛП', 'ВППП', 'ВННН', 'ППН', 'ЛЛЛН', 'НН+Н', 'НННВ', 'ПНН'],
      [false, false, false, false, false, true, true, true, true, false, true, true, false, true, true, true, true, false, true, true, true, false, false, true, false, false, false, false]),
  LevelRoundFixture(10, 10, [[3, 5], [3, 7]], [[6, 7], [0, 5], [0, 2], [3, 8], [5, 0], [4, 4]],
      [1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
      ['ВППП', 'ЛЛЛ', 'НННП', 'ЛПП', 'ННЛЛ', 'ПП+П', 'ННПП', 'ННЛ', 'ННН', 'ВВЛЛ', 'ПВВ', 'ВПП', 'ВВ+В', 'ЛППП', 'НН', 'ВЛЛЛ', 'НН+НН', 'ЛЛЛН', 'ППП+П', 'НЛЛЛ', 'ППНН', 'ЛВВВ', 'Л+ЛЛЛ', 'ПНН', 'ППВВ', 'ВННН', 'НННВ', 'ЛЛ+ЛЛ'],
      [true, false, true, true, true, true, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, true, true, false, true, true, false, false]),
  LevelRoundFixture(10, 10, [[2, 0], [3, 3]], [[2, 3], [5, 9], [8, 8], [1, 9], [5, 0], [9, 6]],
      [0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1],
      ['ВВП', 'Л+ЛЛ', 'ВЛЛЛ', 'ВНН', 'ВЛЛ', 'ЛЛЛЛ', 'ННЛЛ', 'Н+ННН', 'ЛЛЛ+Л', 'ЛЛЛ', 'П+ППП', 'ВВВП', 'НННП', 'НННВ', 'ПВВВ', 'ВВ+ВВ', 'ПНН', 'ППНН', 'ППЛ', 'ВВВ+В', 'ЛЛВВ', 'ВВЛ', 'ЛЛЛП', 'ЛЛ', 'ПППН', 'ПППВ', 'В+ВВВ', 'ВВЛЛ'],
      [false, true, false, true, false, false, false, true, false, false, true, true, true, true, true, false, true, true, true, false, true, false, true, true, false, false, false, false]),
  LevelRoundFixture(10, 10, [[3, 2], [3, 4]], [[6, 4], [8, 4], [6, 6], [6, 2], [6, 5], [2, 9]],
      [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1],
      ['ННН+Н', 'ЛПП', 'ЛЛ+Л', 'ВВП', 'ЛЛП', 'ЛЛВ', 'ЛЛЛ', 'ВЛЛЛ', 'ПННН', 'ВВПП', 'ВВЛЛ', 'ВВВ', 'НЛЛ', 'ЛЛНН', 'Н+НН', 'ЛННН', 'НВВВ', 'НННП', 'ПЛЛ', 'ЛЛ', 'ПП+П', 'ЛЛН', 'ННЛЛ', 'ППНН', 'ЛНН', 'ВННН', 'ЛЛЛ+Л', 'ВВ+ВВ'],
      [true, true, true, true, true, false, true, false, true, true, true, false, false, false, false, false, false, false, true, false, true, false, false, false, true, true, false, true]),
  LevelRoundFixture(10, 10, [[2, 1], [5, 3]], [[5, 5], [6, 3], [8, 2], [8, 4], [3, 5], [9, 7]],
      [1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1],
      ['ЛЛ+ЛЛ', 'Н+НН', 'НВВ', 'ЛППП', 'ВВВЛ', 'ВВВВ', 'ВЛЛЛ', 'ЛЛЛП', 'ВПП', 'ВВЛЛ', 'ЛЛН', 'ЛЛЛ+Л', 'ПВВВ', 'ЛЛ', 'ННПП', 'НН+НН', 'Н+ННН', 'ЛННН', 'ЛЛЛВ', 'ПНН', 'ННЛЛ', 'ПВВ', 'ВВН', 'ВВВП', 'ПППЛ', 'ПППП', 'ВВВ+В', 'ННН+Н'],
      [true, true, true, true, false, false, false, false, false, false, true, false, false, false, true, false, true, true, false, false, false, true, true, true, true, false, true, true]),
];
